mam/config/routes.rb
Mam::Application.routes.draw do
  resources :courses

  resources :buddies

  resources :schools

  match 'schools/:action' => 'schools#:action'

  resources :players

  get "home/index"

  devise_for :users

  root :to => 'home#index'

  match ':controller(/:action(/:id))(.:format)'
end

mam/app/models/school.rb
class School < ActiveRecord::Base
  belongs_to :player

  has_many :courses

  has_many :buddies
  has_and_belongs_to_many :exmembers, :join_table => "buddies_exmembers_of_school", :class_name => "Buddy"

  attr_accessible :description, :logo, :name, :player_id

  has_attached_file :logo, :styles => { :medium => "200x200>", :thumb => "65x65#" }, :default_url =>"default_school_:style.png"

  def members
    self.buddies.select {|buddy| !buddy.waitlist}
  end

  def waitlist
    self.buddies.select {|buddy| buddy.waitlist}
  end

  def teachers
    self.members.find_all { |m| m.is_teacher?}
  end
  
  def students
    self.members.find_all { |m| m.is_student?}
  end

  def idle_members
    self.members - self.teachers - self.students
  end

end

mam/app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  # GET /schools
  # GET /schools.json
  def index
    @schools = School.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @schools }
    end
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
    @school = School.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @school }
    end
  end

  # GET /schools/new
  # GET /schools/new.json
  def new
    @school = School.new
    @players = Player.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @school }
    end
  end

  # GET /schools/1/edit
  def edit
    @school = School.find(params[:id])
    @players = Player.all
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(params[:school])
    @players = Player.all

    age =  38 +rand(6)
    @school.buddies << Buddy.new("waitlist" => true, "age" => age, "skill_exp" => Math.max(500,Buddy::get_skill_exp_for_age(age/2,10+rand(5))))
    5.times do
      @school.buddies << Buddy.new("waitlist" => true)
    end

    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'School was successfully created.' }
        format.json { render json: @school, status: :created, location: @school }
      else
        format.html { render action: "new" }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /schools/1
  # PUT /schools/1.json
  def update
    @school = School.find(params[:id])
    @players = Player.all

    respond_to do |format|
      if @school.update_attributes(params[:school])
        format.html { redirect_to @school, notice: 'School was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school = School.find(params[:id])
    @school.destroy

    respond_to do |format|
      format.html { redirect_to schools_url }
      format.json { head :no_content }
    end
  end

  def add_members
    @school = School.find(params[:school])
    buddy_ids = params[:buddies] ? params[:buddies].keys : []
    buddy_ids.each do |buddy_id|
      buddy = Buddy.find(buddy_id)
      buddy.waitlist = false
      if "Dismiss" == params[:commit]
        buddy.school = nil
      end
      buddy.save

    end

    @school = School.find(params[:school])
    return_to = params[:return_to] || 'schools'
    redirect_to return_to
  end
    
  def dismiss_members
    @school = School.find(params[:school])
    buddy_ids = params[:buddies] ? params[:buddies].keys : []
    buddy_ids.each do |buddy_id|
      buddy = Buddy.find(buddy_id)
      buddy.school.exmembers << buddy
      buddy.school.save
      buddy.school = nil
      buddy.save
    end

    @school = School.find(params[:school])
    return_to = params[:return_to] || 'schools'
    redirect_to return_to
  end

end

mam/app/helpers/schools_helper.rb
module SchoolsHelper
end

mam/app/views/schools/_form.html.erb
<%= form_for @school, :html => {:multipart => true} do |f| %>
  <% if @school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@school.errors.count, "error") %> prohibited this school from being saved:</h2>

      <ul>
      <% @school.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :player_id %><br />
    <%= collection_select(:school, :player_id, @players, :id, :name, {:prompt => false}) %>
  </div>
  <div class="field">
    <%= f.label :logo %><br />
    <%= f.file_field :logo %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

mam/app/views/schools/_list.html.erb
<% if schools %>
<ul>
  <% schools.each do |school| %>
  <li><%= link_to school.name, school %></li>
  <% end %>
</ul>
<% end %>

mam/app/views/schools/_table.html.erb
<table class="table table-bordered table-hover">
  <tr>
    <th rowspan="2">Logo</th>
    <th rowspan="2">Name
      <% unless defined?(skip_player) && skip_player == true %>
      - Player
      <% end %>
      <br/>Description</th>
    <th colspan="3">Statistics</th>
    <th rowspan="2"></th>
    <th rowspan="2"></th>
  </tr>
  <tr>
    <th>Wai</th>
    <th>Mem</th>
    <th>Exm</th>
  </tr>

<% schools.each do |school| %>
  <tr>
    <td><%= link_to image_tag(school.logo.url(:thumb), :class => "img-rounded"), school %></td>
    <td><b><%= link_to school.name, school %></b>
      <% unless defined?(skip_player) && skip_player == true %>
      - <i><%= link_to school.player.name, school.player %></i>
      <% end %>
      <br/><%= school.description %></td>
    <td><%= school.waitlist.size =%></td>
    <td><%= school.members.size =%></td>
    <td><%= school.exmembers.size =%></td>
    <td><%= link_to 'Edit', edit_school_path(school) %></td>
    <td><%= link_to 'Destroy', school, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

mam/app/views/schools/edit.html.erb
<h1>Editing school</h1>

<%= render 'form' %>

<%= link_to 'Show', @school %> |
<%= link_to 'Back', schools_path %>

mam/app/views/schools/index.html.erb
<h1>Listing schools</h1>

<%= render "table", :schools => @schools %>

<br />

<%= link_to 'New School', new_school_path %>

mam/app/views/schools/new.html.erb
<h1>New school</h1>

<%= render 'form' %>

<%= link_to 'Back', schools_path %>

mam/app/views/schools/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
<div class="span3 box">
  <%= image_tag @school.logo.url(:medium), :class => "img-rounded" %>
  <h1><%= @school.name %></h1>
  <i><%= link_to @school.player.name, @school.player %></i>
  <p><%= @school.description %></p>
  <%= link_to 'Edit', edit_school_path(@school) %> |
  <%= link_to 'Back', schools_path %>
</div>
<div class="span9">
  <h2>Buddies</h2>
  <h3>Waitlist</h3>
  <%= render "buddies/selectable_table", :buddies => @school.waitlist, :action => "/schools/add_members", :commits => ["accept", "reject"] %>
  <h3>Members</h3>
  <%= render "buddies/selectable_table", :buddies => @school.members, :action => "/schools/dismiss_members", :commits => ["dismiss"] %>
  <h3>Ex-Members</h3>
  <%= render "buddies/table", :buddies => @school.exmembers %>

  <h2>Courses</h2>
  <%= render "courses/table", :courses => @school.courses %>

</div>
</div>