mam/config/routes.rb
Mam::Application.routes.draw do
  resources :courses

  resources :buddies

  resources :schools

  match 'schools/:action' => 'schools#:action'

  resources :players

  get "home/index"

  devise_for :users

  root :to => 'home#index'

  match ':controller(/:action(/:id))(.:format)'
end

mam/app/models/buddy.rb
require "names"
require "math"

class Buddy < ActiveRecord::Base
  include BuddyDefaultValues
  include BuddyAttributeValues

  belongs_to :school

  has_and_belongs_to_many :exmember_of_schools, :join_table => "buddies_exmembers_of_school", :class_name => "School"

  has_and_belongs_to_many :attending_courses, :join_table => "buddies_attending_courses", :class_name => 'Course'
  has_many :teaching_courses, :foreign_key => "teacher_id", :class_name => 'Course'

  attr_accessible :age, :constitution_exp, :dexterity_exp, :flexibility_exp, :injured, :intelligence_exp, :motivation, :name, :number_of_draws, :number_of_fights, :number_of_wins, :reaction_exp, :school_id, :skill_exp, :speed_exp, :strength_exp, :suitability, :waitlist

  before_save :default_values

  def number_of_losses
    self.number_of_fights - self.number_of_wins - self.number_of_draws
  end

  def waiting_for_school
    self.school if self.waitlist
  end

  def attending_school
    self.school if !self.waitlist    
  end

  def is_teacher?
    not self.teaching_courses.empty?
  end

  def is_student?
    not self.attending_courses.empty?
  end

end

mam/app/controllers/buddies_controller.rb
class BuddiesController < ApplicationController
  # GET /buddies
  # GET /buddies.json
  def index
    @buddies = Buddy.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @buddies }
    end
  end

  # GET /buddies/1
  # GET /buddies/1.json
  def show
    @buddy = Buddy.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @buddy }
    end
  end

  # GET /buddies/new
  # GET /buddies/new.json
  def new
    @buddy = Buddy.new
    @players = Player.all
    @schools = School.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @buddy }
    end
  end

  # GET /buddies/1/edit
  def edit
    @buddy = Buddy.find(params[:id])
    @players = Player.all
    @schools = School.all
  end

  # POST /buddies
  # POST /buddies.json
  def create
    @buddy = Buddy.new(params[:buddy])
    @players = Player.all
    @schools = School.all

    respond_to do |format|
      if @buddy.save
        format.html { redirect_to @buddy, notice: 'Buddy was successfully created.' }
        format.json { render json: @buddy, status: :created, location: @buddy }
      else
        format.html { render action: "new" }
        format.json { render json: @buddy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /buddies/1
  # PUT /buddies/1.json
  def update
    @buddy = Buddy.find(params[:id])
    @players = Player.all
    @schools = School.all

    respond_to do |format|
      if @buddy.update_attributes(params[:buddy])
        format.html { redirect_to @buddy, notice: 'Buddy was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @buddy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buddies/1
  # DELETE /buddies/1.json
  def destroy
    @buddy = Buddy.find(params[:id])
    @buddy.destroy

    respond_to do |format|
      format.html { redirect_to buddies_url }
      format.json { head :no_content }
    end
  end
end

mam/app/helpers/buddies_helper.rb
require 'buddies_helper_charts'

module BuddiesHelper
  
  def buddy_image(buddy, geometry="60x100")
    require "schools_helper"
    
    school_id = 0
    school_id = buddy.attending_school_id if buddy.attending_school_id != nil
    imagename = "/images/tmp/buddy_#{school_id}_#{buddy.belt_color}.png" 
    #if not File.exists?("public/images/#{imagename}")
    image = ImageList.new("gfx/buddy/background.png")
    belt = ImageList.new("public/images/belts/#{buddy.belt_color}_belt.png")
    image.composite!(belt,13,56,OverCompositeOp)
    if buddy.attending_school
      school_logo = ImageList.new("public/#{school_logo_image(buddy.attending_school, "thumb")}")
      school_logo.change_geometry!("14x14") { |cols, rows, img| img.resize!(cols, rows)}
      logo_x = 37-school_logo.columns/2
      logo_y = 47-school_logo.rows/2
      image.composite!(school_logo,logo_x,logo_y,OverCompositeOp)
    end
    image.change_geometry!(geometry) { |cols, rows, img| img.resize!(cols, rows)}
    image.write("public#{imagename}")
    #end
    imagename
  end

end

mam/app/views/buddies/_form.html.erb
<%= form_for(@buddy) do |f| %>
  <% if @buddy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@buddy.errors.count, "error") %> prohibited this buddy from being saved:</h2>

      <ul>
      <% @buddy.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age %><br />
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :school %><br />
    <%= collection_select :buddy, :school_id, @schools, :id, :name, {:include_blank => "None"} %>
  </div>
  <div class="field">
    <%= f.label :waitlist %><br />
    <%= f.check_box :waitlist %>
  </div>
  <div class="field">
    <%= f.label :strength_exp %><br />
    <%= f.number_field :strength_exp %>
  </div>
  <div class="field">
    <%= f.label :constitution_exp %><br />
    <%= f.number_field :constitution_exp %>
  </div>
  <div class="field">
    <%= f.label :dexterity_exp %><br />
    <%= f.number_field :dexterity_exp %>
  </div>
  <div class="field">
    <%= f.label :speed_exp %><br />
    <%= f.number_field :speed_exp %>
  </div>
  <div class="field">
    <%= f.label :flexibility_exp %><br />
    <%= f.number_field :flexibility_exp %>
  </div>
  <div class="field">
    <%= f.label :reaction_exp %><br />
    <%= f.number_field :reaction_exp %>
  </div>
  <div class="field">
    <%= f.label :skill_exp %><br />
    <%= f.number_field :skill_exp %>
  </div>
  <div class="field">
    <%= f.label :intelligence_exp %><br />
    <%= f.number_field :intelligence_exp %>
  </div>
  <div class="field">
    <%= f.label :suitability %><br />
    <%= f.number_field :suitability %>
  </div>
  <div class="field">
    <%= f.label :motivation %><br />
    <%= f.number_field :motivation %>
  </div>
  <div class="field">
    <%= f.label :injured %><br />
    <%= f.number_field :injured %>
  </div>
  <div class="field">
    <%= f.label :number_of_fights %><br />
    <%= f.number_field :number_of_fights %>
  </div>
  <div class="field">
    <%= f.label :number_of_wins %><br />
    <%= f.number_field :number_of_wins %>
  </div>
  <div class="field">
    <%= f.label :number_of_draws %><br />
    <%= f.number_field :number_of_draws %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

mam/app/views/buddies/_selectable_table.html.erb
<% if buddies.size == 0 %>
 - none -
<% else %>
<% commits ||= [] %>
<% id = action[1..-1].gsub("/", "_") %>

<%= form_tag action, :id => id do %>
<% if defined? @school %>
  <%= hidden_field_tag 'school', @school.id %>
  <%= hidden_field_tag 'return_to', url_for(@school) %>
<% end %>
<% if defined? @course %>
  <%= hidden_field_tag 'course', @course.id %>
  <%= hidden_field_tag 'return_to', url_for(@course) %>
<% end %>

<%= render "buddies/table", :buddies => buddies, :selectable => id, :school => nil %>

<div align="right">
<% commits.each do |commit| %>
  <%= submit_tag commit.capitalize%>
<% end %>
</div>

<% end %>

<% end %>

mam/app/views/buddies/_table.html.erb
<% if buddies.size == 0 %>
 - none -
<% else %>
<% selectable ||= false %>

<table class="table table-bordered table-hover" style="width:100%">
  <tr>
    <th rowspan="2">Name&nbsp;(Age)
    <% unless defined?(school) %><br/>
    <i>School</i>
    <% end %></th>
    <th rowspan="2">Belt</th>
    <th colspan="10">Attributes</th>
    <th rowspan="2">injured</th>
    <th>fight stats</th>
    <% if selectable %><th rowspan="2">all<br/><input type="checkbox" class="checkall" /></th><% end %>
    <!--th rowspan="2"></th>
    <th rowspan="2"></th-->
  </tr>
  <tr>
    <th><abbr title="Strength">str</abbr></th>
    <th><abbr title="Constitution">con</abbr></th>
    <th><abbr title="Dexterity">dex</abbr></th>
    <th><abbr title="Speed">spd</abbr></th>
    <th><abbr title="Flexibility">flx</abbr></th>
    <th><abbr title="Reaction">rea</abbr></th>
    <th><abbr title="Skill">skl</abbr></th>
    <th><abbr title="Intelligence">int</abbr></th>
    <th><abbr title="Suitability">sut</abbr></th>
    <th><abbr title="Motivation">mot</abbr></th>
    <th><abbr title="Total/Win/Lose/Draw">T/W/L/D</abbr></th>
  </tr>

<% buddies.each do |buddy| %>
  <tr>
    <td><%= link_to buddy.name, buddy %>&nbsp;(<%= buddy.age %>)
    <% unless defined?(school) %><br/>
    <i><%= link_to buddy.attending_school.name, buddy.attending_school if buddy.attending_school %></i>
    <% end %></td>
    <td><%= image_tag "belts/#{buddy.belt_color}_belt.png" %></td>
    <td><%= buddy.strength %></td>
    <td><%= buddy.constitution %></td>
    <td><%= buddy.dexterity %></td>
    <td><%= buddy.speed %></td>
    <td><%= buddy.flexibility %></td>
    <td><%= buddy.reaction %></td>
    <td><%= buddy.skill %></td>
    <td><%= buddy.intelligence %></td>
    <td><%= buddy.suitability %>%</td>
    <td><%= buddy.motivation %>%</td>
    <td><%= buddy.injured != 0 ? buddy.injured : "- no -" %></td>
    <td><%= buddy.number_of_fights %>/<%= buddy.number_of_wins %>/<%= buddy.number_of_losses %>/<%= buddy.number_of_draws %></td>
    <% if selectable %><td><%= check_box_tag "buddies[#{buddy.id}]", nil, nil, :class =>'check' %></td><% end %>
    <!--td><%= link_to 'Edit', edit_buddy_path(buddy) %></td>
    <td><%= link_to 'Destroy', buddy, method: :delete, data: { confirm: 'Are you sure?' } %></td-->
  </tr>
<% end %>
</table>
<% end %>

mam/app/views/buddies/edit.html.erb
<h1>Editing buddy</h1>

<%= render 'form' %>

<%= link_to 'Show', @buddy %> |
<%= link_to 'Back', buddies_path %>

mam/app/views/buddies/index.html.erb
<h1>Listing buddies</h1>

<%= render "table", :buddies => @buddies %>

<br />

<%= link_to 'New Buddy', new_buddy_path %>

mam/app/views/buddies/new.html.erb
<h1>New buddy</h1>

<%= render 'form' %>

<%= link_to 'Back', buddies_path %>

mam/app/views/buddies/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="span3 box">
    <%= image_tag "buddies/buddy_#{@buddy.belt_color}.png", :class => "img-rounded", :width => 200 %>
    <h1><%= @buddy.name %> (<%= @buddy.age %>)</h1>
    <% if @buddy.injured != 0 %><div class="alert alert-error">Injured: <strong><%= @buddy.injured %></strong></div>
    <% else %><div class="alert alert-success">Not injured</div>
    <% end %>
    <i><%= link_to @buddy.attending_school.name, @buddy.attending_school if @buddy.attending_school %></i>
    <br/>
    <%= link_to 'Edit', edit_buddy_path(@buddy) %> |
    <%= link_to 'Back', buddies_path %>
  </div>
  
  <div class="span9">
    <h2>Attributes</h2>
    <div class="row">
      <div class="span5">
	<% ["strength", "constitution", "dexterity", "speed", "flexibility", "reaction", "skill", "intelligence"].each do |attr| %>
	<%= attribute_badge(@buddy, attr) %>
	<% end %>

	<% {"number_of_fights" => "Fights", "number_of_wins" => "Wins", "number_of_losses" => "Losses", "number_of_draws" => "Draws"}.each do |attr, label| %>
	<%= attribute_badge(@buddy, attr, label) %>
	<% end %>

      </div>
      <div class="span4">
	<%= image_tag attribute_bar_chart_url(@buddy) %>
      </div>
    </div>
    
    <div class="row">
      <div class="span5">
	<% ["suitability", "motivation"].each do |attr| %>
	<%= attribute_badge(@buddy, attr, attr.capitalize, false) %>
	<% end %>
      </div>
      <div class="span4">
	<%= image_tag motivation_bar_chart_url(@buddy) %>
      </div>
    </div>

    <div class="row">
      <div class="span5">
	<% ["actions", "hitpoints", "damage", "resistance"].each do |attr| %>
	<%= attribute_badge(@buddy, attr) %>
	<% end %>
	
	<% {"toHit" => "Hit", "toCriticalHit" => "Critical", "toDefend" => "Defend"}.each do |attr, label| %>
	<%= attribute_badge(@buddy, attr, label, true) %>
	<% end %>
	<%= attribute_badge(@buddy, "injured") %>

	<% {"teachFactor" => "Teaching Factor", "learnFactor" => "Learning Factor"}.each do |attr, label| %>
	<%= attribute_badge(@buddy, attr, label, true) %>
	<% end %>

      </div>
    </div>
    
  </div>
</div>