mam/config/routes.rb
Mam::Application.routes.draw do
  resources :courses

  resources :buddies

  resources :schools

  match 'schools/:action' => 'schools#:action'

  resources :players

  get "home/index"

  devise_for :users

  root :to => 'home#index'

  match ':controller(/:action(/:id))(.:format)'
end

mam/app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @courses }
    end
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    @course = Course.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @course }
    end
  end

  # GET /courses/new
  # GET /courses/new.json
  def new
    @course = Course.new
    @schools = School.all    
    @buddies = Buddy.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @course }
    end
  end

  # GET /courses/1/edit
  def edit
    @course = Course.find(params[:id])
    @schools = School.all
    @buddies = Buddy.all
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(params[:course])
    @schools = School.all
    @buddies = Buddy.all

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render json: @course, status: :created, location: @course }
      else
        format.html { render action: "new" }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /courses/1
  # PUT /courses/1.json
  def update
    @course = Course.find(params[:id])
    @schools = School.all
    @buddies = Buddy.all

    respond_to do |format|
      if @course.update_attributes(params[:course])
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course = Course.find(params[:id])
    @course.destroy

    respond_to do |format|
      format.html { redirect_to courses_url }
      format.json { head :no_content }
    end
  end

  def add_members
    @course = Course.find(params[:course])

    @school = @course.school
    buddy_ids = params[:buddies] ? params[:buddies].keys : []
    if params[:commit] == "Appoint"
      if buddy_ids[0] == nil 
        buddy_ids = []
      else
        buddy_ids = [buddy_ids[0]]
      end
    end
    buddy_ids.each do |buddy_id|
      @buddy = Buddy.find(buddy_id)
      
      @school.courses.each do |course|
        course.removeBuddy(@buddy)
      end
      
      case params[:commit]
        when "Assign"
        @course.addStudent(@buddy)
        when "Appoint"
        @course.setTeacher(@buddy)
        
      end
    end
    
    @course = Course.find(params[:course])
    
    return_to = params[:return_to] || 'courses'
    redirect_to return_to
    
  end

  def remove_teacher
    buddy_ids = params[:buddies] ? params[:buddies].keys : []
    buddy_ids.each do |buddy_id|
      @buddy = Buddy.find(buddy_id)
      
      @course = Course.find(params[:course])
      @course.removeTeacher(@buddy)
    end
    
    @course = Course.find(params[:course])
    
    return_to = params[:return_to] || 'courses'
    redirect_to return_to
    
  end

  def remove_students
    buddy_ids = params[:buddies] ? params[:buddies].keys : []
    buddy_ids.each do |buddy_id|
      @buddy = Buddy.find(buddy_id)
      
      @course = Course.find(params[:course])
      @course.removeBuddy(@buddy)
    end
    
    @course = Course.find(params[:course])
    
    return_to = params[:return_to] || 'courses'
    redirect_to return_to
    
  end

end

mam/app/helpers/courses_helper.rb
require 'courses_helper_charts'

module CoursesHelper

end

mam/app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :school %><br />
    <%= collection_select :course, :school_id, @schools, :id, :name, {:include_blank => "None"} %>
  </div>
  <div class="field">
    <%= f.label :teacher %><br />
    <%= collection_select :course, :teacher_id, @buddies, :id, :name, {:include_blank => "None"} %>
  </div>
  <div class="field">
    <%= f.label :train_strength %><br />
    <%= f.number_field :train_strength %>
  </div>
  <div class="field">
    <%= f.label :train_constitution %><br />
    <%= f.number_field :train_constitution %>
  </div>
  <div class="field">
    <%= f.label :train_dexterity %><br />
    <%= f.number_field :train_dexterity %>
  </div>
  <div class="field">
    <%= f.label :train_speed %><br />
    <%= f.number_field :train_speed %>
  </div>
  <div class="field">
    <%= f.label :train_flexibility %><br />
    <%= f.number_field :train_flexibility %>
  </div>
  <div class="field">
    <%= f.label :train_reaction %><br />
    <%= f.number_field :train_reaction %>
  </div>
  <div class="field">
    <%= f.label :train_skill %><br />
    <%= f.number_field :train_skill %>
  </div>
  <div class="field">
    <%= f.label :train_intelligence %><br />
    <%= f.number_field :train_intelligence %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

mam/app/views/courses/_table.html.erb
<% if courses.size == 0 %>
 - none -
<% else %>

<table class="table table-bordered table-hover">
  <tr>
    <th rowspan="2">Name
    <% unless defined?(school) %><br />
    <i>School</i>
    <% end %></th>
    <th rowspan="2">Teacher</th>
    <th rowspan="2">Students</th>
    <th colspan="8">Training Attributes</th>
    <th rowspan="2">Intensity</th>
    <th rowspan="2">Risk</th>
    <!--th rowspan="2"></th>
    <th rowspan="2"></th-->
  </tr>
  <tr>
    <th><abbr title="Strength">str</abbr></th>
    <th><abbr title="Constitution">con</abbr></th>
    <th><abbr title="Dexterity">dex</abbr></th>
    <th><abbr title="Speed">spd</abbr></th>
    <th><abbr title="Flexibility">flx</abbr></th>
    <th><abbr title="Reaction">rea</abbr></th>
    <th><abbr title="Skill">skl</abbr></th>
    <th><abbr title="Intelligence">int</abbr></th>
  </tr>

<% courses.each do |course| %>
  <tr>
    <td><%= link_to course.name, course %>
    <% unless defined?(school) %><br />
    <i><%= link_to course.school.name, course.school if course.school %></i>
    <% end %></td>
    <td><%= link_to course.teacher.name, course.teacher if course.teacher %></td>
    <td><%= course.students.map { |s| link_to s.name, s }.join(", ").html_safe %></td>
    <td><%= course.train_strength %></td>
    <td><%= course.train_constitution %></td>
    <td><%= course.train_dexterity %></td>
    <td><%= course.train_speed %></td>
    <td><%= course.train_flexibility %></td>
    <td><%= course.train_reaction %></td>
    <td><%= course.train_skill %></td>
    <td><%= course.train_intelligence %></td>
    <td><%= (course.intensity*100).round %>%</td>
    <td><%= (course.risk*100).round %>%</td>
    <!--td><%= link_to 'Edit', edit_course_path(course) %></td>
    <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td-->
  </tr>
<% end %>
</table>
<% end %>

mam/app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

mam/app/views/courses/index.html.erb
<h1>Listing courses</h1>

<%= render "table", :courses => @courses%>

<br />

<%= link_to 'New Course', new_course_path %>

mam/app/views/courses/new.html.erb
<h1>New course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

mam/app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="span3 box">
    <h1><%= @course.name %></h1>
    <i><%= link_to @course.school.name, @course.school if @course.school %></i>
  <br/>
  <%= link_to 'Edit', edit_course_path(@course) %> |
  <%= link_to 'Back', courses_path %>
  </div>

  <div class="span9">
    <h2>Trained Attributes</h2>
    <div class="row">
      <div class="span5">
	<% ["strength", "constitution", "dexterity", "speed", "flexibility", "reaction", "skill", "intelligence"].each do |attr| %>
	<%= attribute_badge(@course, "train_#{attr}", attr.capitalize) %>
	<% end %>

	<%= attribute_badge(@course, "intensity", "Training Intensity", true) %>
	<%= attribute_badge(@course, "risk", "Risk of Injury", true) %>

      </div>
      <div class="span4">
	<%= image_tag attribute_pie_chart_url(@course) %>
      </div>
    </div>
    <h2>Buddies</h2>
    <h3>Teacher</h3>
    <%= render "buddies/selectable_table", :buddies => @course.teachers, :action => "/courses/remove_teacher", :commits => ["suspend"] %>
    <h3>Students</h3>
    <%= render "buddies/selectable_table", :buddies => @course.students, :action => "/courses/remove_students", :commits => ["dismiss"] %>
    <h3>Others</h3>
    <%= render "buddies/selectable_table", :buddies => @course.school.idle_members, :action => "/courses/add_members", :commits => ["assign", "appoint"] %>
  </div>

</div>