mam/config/routes.rb
Mam::Application.routes.draw do
  resources :courses

  resources :buddies

  resources :schools

  match 'schools/:action' => 'schools#:action'

  resources :players

  get "home/index"

  devise_for :users

  root :to => 'home#index'

  match ':controller(/:action(/:id))(.:format)'
end

mam/app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :user
  has_many :schools

  attr_accessible :avatar, :description, :name, :user_id

  has_attached_file :avatar, :styles => { :medium => "200x200>", :thumb => "50x50#" }
end

mam/app/controllers/players_controller.rb
class PlayersController < ApplicationController
  # GET /players
  # GET /players.json
  def index
    @players = Player.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @players }
    end
  end

  # GET /players/1
  # GET /players/1.json
  def show
    @player = Player.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @player }
    end
  end

  # GET /players/new
  # GET /players/new.json
  def new
    @player = Player.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @player }
    end
  end

  # GET /players/1/edit
  def edit
    @player = Player.find(params[:id])
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(params[:player])

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render json: @player, status: :created, location: @player }
      else
        format.html { render action: "new" }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /players/1
  # PUT /players/1.json
  def update
    @player = Player.find(params[:id])

    respond_to do |format|
      if @player.update_attributes(params[:player])
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player = Player.find(params[:id])
    @player.destroy

    respond_to do |format|
      format.html { redirect_to players_url }
      format.json { head :no_content }
    end
  end
end

mam/app/helpers/players_helper.rb
module PlayersHelper
end

mam/app/views/players/_form.html.erb
<%= form_for @player, :html => {:multipart => true} do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :avatar %><br />
    <%= f.file_field :avatar %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

mam/app/views/players/edit.html.erb
<h1>Editing player</h1>

<%= render 'form' %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

mam/app/views/players/index.html.erb
<h1>Listing players</h1>

<table class="table table-bordered table-hover">
  <tr>
    <th>Avatar</th>
    <th>Name<br/>Description</th>
    <th>Schools</th>
    <th></th>
    <th></th>
  </tr>

<% @players.each do |player| %>
  <tr>
    <td><%= link_to image_tag(player.avatar.url(:thumb), :class => "img-rounded"), player %></td>
    <td><%= link_to player.name, player %><br/><%= player.description %></td>
    <td><%= render "schools/list", :schools => player.schools %></td>
    <td><%= link_to 'Edit', edit_player_path(player) %></td>
    <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Player', new_player_path %>

mam/app/views/players/new.html.erb
<h1>New player</h1>

<%= render 'form' %>

<%= link_to 'Back', players_path %>

mam/app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
<div class="span3 box">
  <%= image_tag @player.avatar.url(:medium), :class => "img-rounded" %>
  <h1><%= @player.name %></h1>
  <p><%= @player.description %></p>
  <%= link_to 'Edit', edit_player_path(@player) %> |
  <%= link_to 'Back', players_path %>
</div>
<div class="span9">
  <h2>Schools</h2>
  <%= render "schools/table", :schools => @player.schools, :skip_player => true %>
</div>
</div>